### ISSUE TITLE
Tarefas iniciais backend

### ISSUE THREAD

**Issue by RenatoNr** [RenatoNr/Backend-Registro-de-Ponto-CTEDS#2]
### Tasks 

- [x] Primeiro commit
- [x] Criação das pastas padrão Repository
- [x] Definição das Models
- [x] Configurar Entity Framework
- [x] Implementar Controllers
- [x] Criar repositório
